default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: clark_dev

test:
  <<: *default
  database: clark_test

production:
  <<: *default
  database: clark_prod
